### ISSUE TITLE
What happened to Mali support?

### ISSUE THREAD

**Issue by pwpiwi** [gtelwifi/manifest#3]
Compiled successfully and runs fine. I have noticed that you have removed Mali-Sources from the Samsung kernel sources. Is there a specific reason?

**Comment by codeworkx** [comment]
And what's this https://github.com/gtelwifi/android_kernel_samsung_gtelwifi/tree/cm-11.0/drivers/gpu/mali then? Looks like mali sources.

**Comment by pwpiwi** [comment]
Oops. I stand corrected. Mali sources just moved to another place. :flushed:
